### ISSUE TITLE
图生图运行之后报错

### ISSUE THREAD

**Issue by frankiegu** [mylxsw/aidea-server#25]
图生图运行之后，七牛回调接口报"token":"","err_code":401,"error":"auth failed: invalid auth type"

**Comment by mylxsw** [comment]
检查七牛云相关配置是否正确以及是否在七牛云开通了对象存储服务。

```yaml
# 用于提供图片存储服务，图片上传、图片下载、缩略图生成等

storage-appkey: ""
storage-secret: ""
storage-bucket: "aicode"
storage-callback: "https://ai-api.example.com/v1/callback/storage/qiniu"
# 七牛云存储区域，可选值：
# 华东 - z0
# 华北 - z1
# 华南 - z2
# 南美 - na0, 
# 新加坡 - as0
# 华东浙江 2 区 - cn-east-2
# 亚太首尔 1 区 - ap-northeast-1
storage-region: "z0"
```
